[colors.primary]
background = "#171421"

[env]
ALACRITTY = "true"
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "Mononoki Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Mononoki Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Mononoki Nerd Font Mono"
style = "Italic"

[font.glyph_offset]
y = 1

[font.offset]
x = 2
y = 12

[window]
blur = true
decorations = "none"
dynamic_padding = true
opacity = 0.9
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
