theme = "fleet_dark"

[editor]
true-color = true
cursorline = true
color-modes = true
auto-format = true
line-number = "relative"
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-type"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position"]

[editor.indent-guides]
render = true

[editor.lsp]
auto-signature-help = false

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
# C-s = ':w' # save current buffer
# y = "yank_main_selection_to_clipboard"
# p = "paste_clipboard_after"
# P = "paste_clipboard_before"
